//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AmoghReports.WebSite.RFITransmittalWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RFITransmittalServiceSoap", Namespace="http://maakuthari.com/")]
    public partial class RFITransmittalService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RegisterRFITransmittalDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RFITransmittalService() {
            this.Url = global::AmoghReports.WebSite.Properties.Settings.Default.AmoghReports_WebSite_RFITransmittalWebservice_RFITransmittalService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RegisterRFITransmittalDetailsCompletedEventHandler RegisterRFITransmittalDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://maakuthari.com/RegisterRFITransmittalDetails", RequestNamespace="http://maakuthari.com/", ResponseNamespace="http://maakuthari.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RegisterRFITransmittalDetails(int ProjId, string RFI_Number, int SUB_CON_ID, string Inspector_Name, string Inspection_Date, string Item_Desc, string Inspection_Result) {
            object[] results = this.Invoke("RegisterRFITransmittalDetails", new object[] {
                        ProjId,
                        RFI_Number,
                        SUB_CON_ID,
                        Inspector_Name,
                        Inspection_Date,
                        Item_Desc,
                        Inspection_Result});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterRFITransmittalDetailsAsync(int ProjId, string RFI_Number, int SUB_CON_ID, string Inspector_Name, string Inspection_Date, string Item_Desc, string Inspection_Result) {
            this.RegisterRFITransmittalDetailsAsync(ProjId, RFI_Number, SUB_CON_ID, Inspector_Name, Inspection_Date, Item_Desc, Inspection_Result, null);
        }
        
        /// <remarks/>
        public void RegisterRFITransmittalDetailsAsync(int ProjId, string RFI_Number, int SUB_CON_ID, string Inspector_Name, string Inspection_Date, string Item_Desc, string Inspection_Result, object userState) {
            if ((this.RegisterRFITransmittalDetailsOperationCompleted == null)) {
                this.RegisterRFITransmittalDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterRFITransmittalDetailsOperationCompleted);
            }
            this.InvokeAsync("RegisterRFITransmittalDetails", new object[] {
                        ProjId,
                        RFI_Number,
                        SUB_CON_ID,
                        Inspector_Name,
                        Inspection_Date,
                        Item_Desc,
                        Inspection_Result}, this.RegisterRFITransmittalDetailsOperationCompleted, userState);
        }
        
        private void OnRegisterRFITransmittalDetailsOperationCompleted(object arg) {
            if ((this.RegisterRFITransmittalDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterRFITransmittalDetailsCompleted(this, new RegisterRFITransmittalDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RegisterRFITransmittalDetailsCompletedEventHandler(object sender, RegisterRFITransmittalDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterRFITransmittalDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterRFITransmittalDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591